<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/gestiones.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/modalSuscripciones.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/gridGestiones.js"?>"></script>


<style type="text/css" media="all">
    /* fix rtl for demo */
    .chosen-rtl .chosen-drop { left: -9000px; }
    .wrapColumnText 
    { 
           white-space: normal !important; 
           height:auto; 
           vertical-align:text-top; 
    }  
</style>

<div>
<div class="panel-default "  align=center>
            <div class="row well" style="width:100%;">
                <h1>ALTA GESTIONES</h1> 
            </div>
             <div class="alert alert-danger" id="warning-modal" style="display: none;">
                    <div id="warning-message-modal"></div>
            </div>
            <div class="alert alert-success"  id="success-modal" style="display: none;">
                    <div id="success-message-modal"></div>
            </div> 
            <div class="modal-body">
                <div class="container"> 
                    <div class="row">

                        <div class="col-lg-8">
                            <div class="form-group col-lg-3 hide">
                                <!-- <label class="col-lg-6 control-label">Gestion:</label> -->
                                <div class="col-lg-12">
                                    <input name="codigogestion-modal" id="codigogestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Cliente:</label>
                                <div class="col-lg-7">
                                    <select id="cliente-modal" class="" style="width: 100%;">
                                    </select>
                                </div>
                                <div class="col-lg-3">
                                    <input name="tipocliente-modal" id="tipocliente-modal" class="form-control input-sm"></input>
                                    <input name="tipoclientecodigo-modal" id="tipoclientecodigo-modal" class="hide"></input>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Fecha:</label>
                                <div class="col-lg-7">
                                    <input name="fechagestion-modal" id="fechagestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                        </div>
                    </div >
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Tarea:</label>
                                <div class="col-lg-10">
                                    <textarea class="form-control" id="tarea-modal" placeholder="Ingrese comentario" rows="6" maxlength="1500"> </textarea>
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4"> 
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Inicio:</label>
                                <div class="col-lg-7">
                                    <input name="iniciogestion-modal" id="iniciogestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Fin:</label>
                                <div class="col-lg-7">
                                    <input name="fingestion-modal" id="fingestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Tiempo Estimado:</label>
                                <div class="col-lg-5">
                                    <input name="tiempoestimado-modal" type="number" id="tiempoestimado-modal" class="form-control input-sm"></input>
                                </div>
                                <div class="col-lg-2"> <span>min</span></div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Cant gestiones:</label>
                                <div class="col-lg-5">
                                    <input name="cantidadgestion-modal" type="" id="cantidadgestion-modal" class="form-control input-sm"></input>
                                </div>
                                <div class="col-lg-2"> <span>uni</span></div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Asignado a:</label>
                                <div class="col-lg-10">
                                    <select id="asistenteservicios-modal"  class="" style="width:100%;">
                                     
                                    </select>
                                    <!-- <input name="gestor-modal" id="gestor-modal" class="form-control input-sm"></input> -->
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Estado:</label>
                                <div class="col-lg-7">
                                    <!-- <input name="cantidadgestion-modal" id="cantidadgestion-modal" class="form-control input-sm"></input> -->
                                    <select id="estado-modal" class="input-sm form-control">
                                        <option value="-1">Seleccione</option>
                                        <option value="P">Pendiente</option>
                                        <option value="E">En Proceso</option>
                                        <option value="F">Finalizado</option>
                                        <option value="A">Anulado</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Plan activo:</label>
                                <div class="col-lg-10">
                                    <ul class="list-group" id="planactivo-modal">
                                     </ul>
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Saldo:</label>
                                <div class="col-lg-5">
                                    <input name="saldogestion-modal" id="saldogestion-modal" class="form-control input-sm"></input>
                                </div>
                                <div class="col-lg-2"> <span>uni</span></div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label"> Enviar email:</label>
                                <div class="col-lg-5">
                                    <input id="enviaremail-modal" type="checkbox" name="vehicle" value="SI" > Si<br>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label"> Gentileza:</label>
                                <div class="col-lg-5">
                                    <input id="gentileza-modal" type="checkbox" name="" value="S" > Si<br>
                                </div>
                            </div>
                        </div>
                    </div>
                    

                </div>
           </div>
        <div class="modal-footer">
            <a  id="cancelar-modal"class="btn btn-danger">Cancelar</a>
            <a id="guardar-modal" class="btn btn-success">Guardar</a>
        </div>
        </div>    



    <!-- </div>    end   panel body -->
</div> <!-- end panel default -->

   
</div>
  <script type="text/javascript">
$(document).ready(function() { 
$("#hora-track").datetimepicker();
$("#cliente-modal").select2();
$("#asistenteservicios-modal").select2();
$("#cliente-modal-suscripcion").select2();
$("#asistenteservicios-modal-suscripcion").select2();
$("#planactivo-modal-suscripcion").select2(); 
});

  </script>




